INSERT INTO <SCH><THIP>PARAM_PSN (ID_PROGRESSIVO, ID_FUNZIONE, ID_PARAMETRO, ID_AZIENDA, DESCRIZIONE, DESCR_RIDOTTA, R_RIFER_ATTRIB, VALORE_PARAM, STATO, R_UTENTE_CRZ, R_UTENTE_AGG, NOTA, AREA, NUMERO_FIX) VALUES (<NUM><PARAM_PSN>, 'YImmaginiCatalogo', 'RelazioniEscludere', null, 'Relazioni da escludere', 'Relazioni da es', 'WhereCondition', 'Articolo', 'V', <USER>, <USER> , null, '-' , null);
INSERT INTO <SCH><THIP>PARAM_PSN_L (ID_PROGRESSIVO, ID_LINGUA, DESCRIZIONE, DESCR_RIDOTTA) VALUES (<LAST_NUM><PARAM_PSN>,'it', 'Relazioni da escludere', 'Relazioni da es');

INSERT INTO <SCH><THIP>PARAM_PSN (ID_PROGRESSIVO, ID_FUNZIONE, ID_PARAMETRO, ID_AZIENDA, DESCRIZIONE, DESCR_RIDOTTA, R_RIFER_ATTRIB, VALORE_PARAM, STATO, R_UTENTE_CRZ, R_UTENTE_AGG, NOTA, AREA, NUMERO_FIX) VALUES (<NUM><PARAM_PSN>, 'YImmaginiCatalogo', 'PercorsoSalvataggio', null, 'Percorso salvataggio immagini catal', 'Percorso salvat', 'FileName', 'W:\PthDev\Projects\Panthera\Valvorobica\WebContent', 'V', <USER>, <USER> , null, '-' , null);
INSERT INTO <SCH><THIP>PARAM_PSN_L (ID_PROGRESSIVO, ID_LINGUA, DESCRIZIONE, DESCR_RIDOTTA) VALUES (<LAST_NUM><PARAM_PSN>,'it', 'Percorso salvataggio immagini catal', 'Percorso salvat');


