 
# ownere: THIP_PERS
    # OWNER
    INSERT INTO <SCH>FW_DATA_OWNER (ID, DESCRIPTION) VALUES ('THIP_PERS', 'Personalizzazioni THIP');
 
# ownere: THIP_PERS
    # OWNER
    INSERT INTO <SCH>FW_DATA_OWNER (ID, DESCRIPTION) VALUES ('THIP_PERS', 'Personalizzazioni THIP');
 
# ownere: THIP_PERS
    # OWNER
    INSERT INTO <SCH>FW_DATA_OWNER (ID, DESCRIPTION) VALUES ('THIP_PERS', 'Personalizzazioni THIP');
 
# ownere: THIP_PERS
    # OWNER
    INSERT INTO <SCH>FW_DATA_OWNER (ID, DESCRIPTION) VALUES ('THIP_PERS', 'Personalizzazioni THIP');
